name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  docker:
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build -t capturely-api:latest .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag image
        run: |
          docker tag capturely-api:latest ${{ secrets.DOCKER_USERNAME }}/capturely-api:latest
          docker tag capturely-api:latest ${{ secrets.DOCKER_USERNAME }}/capturely-api:${{ github.sha }}

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/capturely-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/capturely-api:${{ github.sha }}

      - name: Cleanup local Docker images
        run: |
          docker rmi capturely-api:latest || true
          docker rmi ${{ secrets.DOCKER_USERNAME }}/capturely-api:latest || true
          docker rmi ${{ secrets.DOCKER_USERNAME }}/capturely-api:${{ github.sha }} || true

          docker image prune -f